### ISSUE TITLE
Add Support for UTF-8 

### ISSUE THREAD

**Issue by italiana** [jlolling/talendcomp_tJSONDoc#11]
The pre-installed tFileInputJSON component has the ability to select encoding between UTF-8 and other different types of encoding. The current component seems to fail to read UTF-8 charactors.

**Comment by italiana** [comment]
My bad, seems that the encoding is automatically detected based on the documentation on jackson, I had issued only because my output wasn't configured properly.
Again though really nice tool, saved my day!

**Comment by jlolling** [comment]
Do not worry, You are welcome.
