### ISSUE TITLE
Real Life Example Code?

### ISSUE THREAD

**Issue by hypertoast** [jlolling/talendcomp_tJSONDoc#12]
@jlolling 
This looks very promising. The documentation is thorough. Would it be possible to share example talend jobs which we can import and actually see it working?

Thank you!

**Comment by jlolling** [comment]
Yes, I have some example job. I will export them and provide them here. It will take some days.

**Comment by hypertoast** [comment]
@jlolling Is it possible to upload a working example please? I have another need for manipulating JSON document. Any help is appreciated. Thanks.

**Comment by SanjayKhankari** [comment]
@jlolling It would be great help if you share examples for formatting json using tJSONDocOutput and tJSONDocSave components

**Comment by jlolling** [comment]
Hi Sanajay, could your please describe a scenario which you have in mind? I will try to setup a job to fit your requirements.

**Comment by hypertoast** [comment]
@jlolling I have been trying to use this component for quite some time. One simple example I am trying to do is below. Can you share some examples if I had to create this object from scratch? The current talend component is not well documented/ flexible. Thanks:
`parent child
-------- -----
a            ca
a            cb
a            cc
`
I am trying to make a json object:
`
{
	"parentid": "a",
	"child": [{
			"child-name": "ca"
		},
		{
			"child-name": "cb"
		},
		{
			"child-name": "cc"
		}
	]
}
`
