### ISSUE TITLE
Empty array or object for child objects in case there are no child objects

### ISSUE THREAD

**Issue by jlolling** [jlolling/talendcomp_tJSONDoc#15]
If child objects will be assigned to a parent object via a foreign key relation in a next tJSONDocOutput component the target array (or object) will only be created in case of there are child objects.
It is supposed to have an option to create an empty array or object in case of there are no children.

**Comment by blag001** [comment]
Anything new on this subject ?

It's really a bug more than an enhancement for me :/

As for now, there is no way to build the flowing JSON : 
```
[
  {
    "id":1
    "payload": [
      {"value": "123"},
      {"value": "456"}
    ]
  },
  {
    "id":2
    "payload": []
  }
]
```

**Comment by jlolling** [comment]
I will check that now. In my projects this was not an issue because we do not expect an empty array - actually I was forced to remove empty arrays.

**Comment by jlolling** [comment]
I have checked this issue and I do not have a solution which creates and empty array by the data from the referencing components via foreign key relations in case of there is no child record. 
The problem is because I have no record I do not have a foreign key and cannot address the parent object. The only way is to write an empty array while writing the parent object. 
I am thinking about a function which checks at the end of the flow to add empty arrays for not referenced parent objects.

**Comment by jlolling** [comment]
You can use a workaround (actually it is a good solution) and add the empty array just in the parent object while filling it.
You could write simply the "payload" attribute in the parent with "[]" as value and mark this column as "Is a JSON object" (means it will take this empty array as real array and not as String.

**Comment by blag001** [comment]
I'll try that now, I was playing with an empty List in my tMap for the parent, but without success.

The string `[]` as JSON didn't hit my mind, but that'll probably do exactly what I want.

This is a great set of component you've made ;)
If I figure exactly how everything work, I'll probably make a pull request to improve the example documentation, if you don't mind.

BTW, The compatibility is for 6.*, but I'm using it with 5.6 without any problem, do you know some bug with 5.6 or it's just not _officially_ supported ?

**Comment by jlolling** [comment]
This component works also in 5.x projects. I have a customer doing that.
