### ISSUE TITLE
Catching json schema error validation

### ISSUE THREAD

**Issue by blag001** [jlolling/talendcomp_tJSONDoc#16]
Hi, 

I can't find a way to catch the error throw when validating a schema, is there a way ?

For now, using `OnComponentError->` and `row8.content = (String)globalMap.get("tJSONDocSave_1_ERROR_MESSAGE");` I can get some output.

![image](https://user-images.githubusercontent.com/6142277/36680718-dccdd794-1b16-11e8-9d27-34ae8f517038.png)

>error: string "971" is too long (length: 3, maximum allowed: 2)
>error: string "01" is too short (length: 2, required minimum: 3)

But I don't have any context about where this occur... 

Same, it seem `[$id, examples]` are not supported, even if they are in the last JSON Schema, what are the version supported ?

Thanks,
Blag

**Comment by jlolling** [comment]
I will improve the error message with the suggested pointer.

**Comment by jlolling** [comment]
This is the result of my tests:
`error: pointer "": object instance has properties which are not allowed by the schema: ["created_byX"]
error: pointer "/properties/participation/properties/pseudonym/properties/firstname": instance type (null) does not match any allowed primitive type (allowed: ["string"])
error: pointer "/properties/participation/properties/pseudonym/properties/name_supplement": instance type (null) does not match any allowed primitive type (allowed: ["string"])
error: pointer "/properties/participation/properties/pseudonym/properties/pseudonym_id": instance type (null) does not match any allowed primitive type (allowed: ["integer"])
error: pointer "/properties/participation/properties/pseudonym/properties/salutation": instance type (null) does not match any allowed primitive type (allowed: ["string"])
error: pointer "/properties/participation/properties/rolenames/items": object instance has properties which are not allowed by the schema: ["default_selectionX"]`

**Comment by jlolling** [comment]
BTW, in your job it would be easier to use a tFixedFlowInput component to send the error message in the row8.

**Comment by blag001** [comment]
Thanks again for your time ;)

You said you don't have a pointer in case of unwanted properties, but then you have it here:
> [error] /properties/participation/properties/rolenames/items: object instance has properties which are not allowed by the schema: ["default_selectionX"]

Do I miss something ?

Thanks for the tFixedFlowInput tip, that was what I was after, but I was not able to remember the component name.

**Comment by jlolling** [comment]
Yes, the schema validator is better than thought.
I have published the new components on Github, unfortunately I was not able
to publish them on Talend Exchange yet.

Https://github.com/jlolling

Best regards
Jan

Am 02.03.2018 8:16 vorm. schrieb "Blag" <notifications@github.com>:

**Comment by blag001** [comment]
Not that bad, thanks again, I'm already using the master, don't worry about Talend Exchange.

On http://json-schema-validator.herokuapp.com/ using:
`{"ZONES":[{"a":12},{"a":5},{"a":null}]}{"ZONES":[{"a":12},{"a":5},{"a":null}]}`
against 
`{"type":"object","properties":{"ZONES":{"type":"array","items":{"type":"object","properties":{"a":{"type":"integer",}}}}}}`

You got this kind of pointer:

```
[ {
  "level" : "error",
  "schema" : {
    "loadingURI" : "#",
    "pointer" : "/properties/ZONES/items/properties/a"
  },
  "instance" : {
    "pointer" : "/ZONES/2/a"
  },
  "domain" : "validation",
  "keyword" : "type",
  "message" : "instance type (null) does not match any allowed primitive type (allowed: [\"integer\"])",
  "found" : "null",
  "expected" : [ "integer" ]
} ]
```

The ` "pointer" : "/ZONES/2/a"` mean you can make a join to show exactly where the error is.

But I think you're not using the same java lib to make the validation ?

Best wishes,
Blag

**Comment by jlolling** [comment]
I am using the json-schema library. I will take a look at your suggestion.

**Comment by jlolling** [comment]
This issue is solved now. Both components dealing with validation have an additional option to prevent the component from dying.
There is also a additional component providing a flow with all errors.
