### ISSUE TITLE
Improve Error message from Validation

### ISSUE THREAD

**Issue by blag001** [jlolling/talendcomp_tJSONDoc#17]
Hello,

Could you change the following part : 
https://github.com/jlolling/talendcomp_tJSONDoc/blob/3b5e2f8aea15bf6763b617cf3bb3ce2596fab5da/src/main/java/de/jlo/talendcomp/json/JsonDocument.java#L1337-L1357

To include the Schema pointer given by:

```
JsonNode jsonNode = processingMessage.asJson();
String fieldJsonSchemaPath = jsonNode.get("schema").get("pointer").toString();
```

_From https://github.com/java-json-tools/json-schema-validator/issues/193#issuecomment-235496829_ 

It'll greatly improve the quality of the Error output.

It seem not a big patch, but I'm not good enough with java to make it by myself (or to recompile the project after, to be precise).

Kind regards,
Blag

**Comment by jlolling** [comment]
Hi Blag,

sounds good but it seems the pointer is mostly not filled - especially on errors we would like to have it (missing fields or unwanted fields) - that says the comment from sharonbn1.

I will add you suggestion but I am not sure if it really helps.

**Comment by blag001** [comment]
Hi!

Yes this is sadly not a perfect solution, you're right, but as I'll mostly use the JSON-Schema to enforce rules on my data, having a pointer of "where" in my 1M row file will be a great progress ;)

Thanks again

**Comment by jlolling** [comment]
I have updated the component to version 13.0 which contains all possible improvements (so far).
