### ISSUE TITLE
Add `Die on error` feature

### ISSUE THREAD

**Issue by blag001** [jlolling/talendcomp_tJSONDoc#18]
Hello, 

Do `tJSONDocSave` provide a `Die on error` option ? I can't find one and need to use a `OnComponentError->tDie` to kill the parent job...

Could be a good idea to add one, like other read/write component.

Best regards,

**Comment by jlolling** [comment]
A Die On Error option is currently not implemented. But it means the component "dies" on error.
You can use the OnComponentError or staring at the sub job start the OnSubjobError trigger just now.

**Comment by blag001** [comment]
Die On Error enabled component allow OnComponentError processing if I remember, no ? 
They just finish the job with an error without the need of a tDie and kill parent with "die on child error" enable ?

(It's just I have to use a `tDie` every time, and if I forget the job won't stop by himself)
