### ISSUE TITLE
Error type on tJSONDocOpen/Save

### ISSUE THREAD

**Issue by blag001** [jlolling/talendcomp_tJSONDoc#19]
Hi,

I would like to log the error from JSON-Schema validation in a different file of my "runtime-error".

For now I catch all `tJSONDocSave_1_ERROR_MESSAGE` as json-schema error, but sometime I got Talend File Open error without any way to prevent this...

And same on the other way, in my runtime-error I catch the full json-schema error (this may be acceptable).

Could you add an `ERROR_CODE` we could check, or another way to find the nature of the error ?

Thanks a lot,

**Comment by jlolling** [comment]
I agree with you. I will add the necessary output.

**Comment by blag001** [comment]
Thanks again for your time!

**Comment by jlolling** [comment]
This is in the current development version now solved. You can decide to let the component not to let die if the validation detects errors and you can get the errors in detail in the component tJSONDocValidationInput (referencing the component performing the validation).
