### ISSUE TITLE
SLF4J: Class path contains multiple SLF4J bindings

### ISSUE THREAD

**Issue by blag001** [jlolling/talendcomp_tJSONDoc#20]
Hello, 

I'm using Talend ESB and the components `tRESTRequest` / `tRESTResponse` to make a REST webservice and try to use as a back end the tJSONDoc*, but without any success...

I'm getting the following error :

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/xxx/workspace/.Java/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/xxx/workspace/.Java/lib/slf4j-simple-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
Prepare json schema for id: InsertJsonChild.tJSONDocOpen_2
Exception in component tJSONDocOpen_2 (InsertJsonChild)
java.lang.IllegalStateException: Clones objects detected! Use the latest Jayway library 2.2.1+
	at de.jlo.talendcomp.json.JsonDocument.<init>(JsonDocument.java:131)
	at local_project.insertjson_0_1.InsertJsonChild.tJSONDocOpen_2Process(InsertJsonChild.java:969)
	at local_project.insertjson_0_1.InsertJsonChild.tFileInputRaw_2Process(InsertJsonChild.java:728)
	at local_project.insertjson_0_1.InsertJsonChild.runJobInTOS(InsertJsonChild.java:1477)
	at local_project.insertjson_0_1.InsertJsonChild.main(InsertJsonChild.java:1216)
```

It seem to be linked with the #14  issue.

Do you have any idea of how we can manage to make them work together ?

**Comment by jlolling** [comment]
This happens if you mix the build-in Talend JSON component tExtractFieldJSON with my JSON components.
The tRESTRequest and tRESTResponse component does not cause any problems - I do the same.

**Comment by blag001** [comment]
Hi @jlolling  
I'm pretty sure we don't use any native JSON components in this job, I'll ask to be assured.

Could you share some screenshot of a basic REST web-service using tJSONDoc* ? 
We probably miss something on our side if you're able to make them work together.

Best wish

**Comment by jlolling** [comment]
[tug_20180215_gvl_core_webservices.pdf](https://github.com/jlolling/talendcomp_tJSONDoc/files/1847223/tug_20180215_gvl_core_webservices.pdf)
I had made a presentation about creating web services with Talend DI and these JSON components.
I am sorry, this file is in German but you will get an idea about the design because of the screenshots.

**Comment by jlolling** [comment]
Could you please go to the advanced settings of the tJSONDocOpen and tell me the component version?
Please take care you do not have the build-in json components also in no other parent, child or embedded job of you current job (running within the same JVM instance).

**Comment by jlolling** [comment]
The sl4j binding problem is not the problem, the problem is the out-dated jayway library you have in your classpath of the job.

**Comment by sounajd** [comment]
Hi @jlolling 

I am working with blag001 on the same Job, the tJsonDocOpen's version is **13.0**, I think it is the latest version,
is there any possibility to update the Jayway Library ?

**Comment by jlolling** [comment]
Could you tell me the Talend Studio version you use please?
And it would be great to have an exported job item - if possible.
Otherwise I can offer, we meet us per skype.

**Comment by jlolling** [comment]
Your latest screenshot show only the problem with the logging. Actually this is not really a problem.
The much more dangerous problem was the wrong jayway library but this is not the case in you last shown job.
My json components does not use sl4j and does not ships the log4j library. So I am pretty sure the error message from sl4j will persist if you remove my component.
