### ISSUE TITLE
Value if attribute is missing 

### ISSUE THREAD

**Issue by robertrichter** [jlolling/talendcomp_tJSONDoc#23]
Hi Jan...Unfortunately I'm not able to get the value out of the field "value if the attribute is missing" in tJSONDocInput. Here is my json and the component configuration. 

I would like to check, if the field exterior is present or not. As you can see in adId=1 there is no exteriror, but the component delivers "[]" and not "false". Can you please give me a hint how I can achieve this, or is this a bug?

`{
   "images": [
      {
         "adId": "1",
         "customerId": "1",
         "interior": {
            "reference": "unknown",
            "initiator": "unknown",
            "initiatorRole": "unknown",
            "channel": "UNKNOWN"
         }
      },
      {
         "adId": "2",
         "customerId": "1",
         "exterior": {
            "reference": "unknown",
            "initiator": "360test",
            "initiatorRole": "USER",
            "channel": "APP"
         },
         "interior": {
            "reference": "unknown",
            "initiator": "unknown",
            "initiatorRole": "unknown",
            "channel": "UNKNOWN"
         }
      }
   ]
}`

<img width="746" alt="component" src="https://user-images.githubusercontent.com/5345384/46519821-0a597400-c87a-11e8-983b-1ff247ff597d.PNG">
<img width="605" alt="output" src="https://user-images.githubusercontent.com/5345384/46519822-0a597400-c87a-11e8-8d98-da53f58b95de.PNG">

**Comment by jlolling** [comment]
Missing means the attribute does not exists! In your case the attribute is present - but has perhaps a empty or null value. This does not mean it is missing!
Sorry for the late answer. Please call me directly in case you have a urgent issue!

**Comment by robertrichter** [comment]
Thanks...I totally missed that I opened this issue. The main problem was the leading dot for each field.
