### ISSUE TITLE
Schema Validation: Allow filtering of rejects

### ISSUE THREAD

**Issue by cyroxx** [jlolling/talendcomp_tJSONDoc#25]
In a current use case, it would like to be able to distinguish between valid and invalid JSON objects in a way that they end up in different flows (main(/filter) and reject) - similar to `tXSDValidator`. In the schema for the reject flow, an `errorMessage` column contains all validation error messages for that particular JSON.

I do not know whether it is possible to have a meaningful `errorCode` column, especially in the case of multiple validation errors.

Possible extensions of this feature:
- An option to specify the separator that is used between the different validation errors in the `errorMessage` column.
- An option to emit one row on the reject flow for each validation error (default: false).

**Comment by jlolling** [comment]
This is an example of error messages:
`error: object instance has properties which are not allowed by the schema: ["created_byX"]
error: instance type (null) does not match any allowed primitive type (allowed: ["string"])
error: instance type (null) does not match any allowed primitive type (allowed: ["string"])
error: instance type (null) does not match any allowed primitive type (allowed: ["integer"])
error: instance type (null) does not match any allowed primitive type (allowed: ["string"])
error: object instance has properties which are not allowed by the schema: ["default_selectionX"]`

**Comment by jlolling** [comment]
I am currently switch to a much faster and much more expressive schema validator.
This is a test output of the new schema validator:
`[additionalProperties] $.created_byX: is not defined in the schema and the schema does not allow additional properties
[additionalProperties] $.participation.rolenames[1].default_selectionX: is not defined in the schema and the schema does not allow additional properties
[type] $.participation.pseudonym.firstname: null found, string expected
[type] $.participation.pseudonym.name_supplement: null found, string expected
[type] $.participation.pseudonym.pseudonym_id: null found, integer expected
[type] $.participation.pseudonym.salutation: null found, string expected`

**Comment by jlolling** [comment]
We will get a new component tJSONDocValidationInput which provides a flow containing all validation errors in detail (json path to the problem, type of problem, message).
This component points to a validating component like tJSONDocOpen or tJSONDocSave.
