### ISSUE TITLE
POM build fails due to missing dependency `talend-job-mock`

### ISSUE THREAD

**Issue by cyroxx** [jlolling/talendcomp_tJSONDoc#26]
I was trying to run the test cases using TravisCI. Unfortunately, it failed because `de.cimt.talend.mock:talend-job-mock` could not be found. Details: https://travis-ci.org/cyroxx/talendcomp_tJSONDoc/builds/495669684

How about releasing `talend-job-mock` in Maven Central to fix this issue?

**Comment by jlolling** [comment]
In the current development branch this problem is solved
