### ISSUE TITLE
failure while streaming multiple array elements

### ISSUE THREAD

**Issue by robertrichter** [jlolling/talendcomp_tJSONDoc#27]
Hi...I have attached a sample json file and talend job (version 6.4.1) to reproduce the behaviour.
[test_data.txt](https://github.com/jlolling/talendcomp_tJSONDoc/files/3186927/test_data.txt)
[test_json.zip](https://github.com/jlolling/talendcomp_tJSONDoc/files/3186931/test_json.zip)

Let's assume you have multiple arrays within a json element like the following and you want to read all sub elemts of the array together with the header information.
```
[
  {  
      "header":"global header1",
	  "items":[{...},{...}],
	  "more_items":[{...},{...}]
  }
]
```

I have configured the components according to your documentation and this works pretty good, except for the second array element _more_items_. For all elements except the first element in _more_items_, I receive NULL as header value. To make this a bit more transparent I have attached the log. I'm not sure if this is a failure in configuration, the component or maybe in the streaming api itself. It's possible to solve this by using the basic tJSONDocInput component instead of the tJSONDocInputStream, but it would be great to do this in streaming mode for large json files. Hope you can help me.

```
.--------------+-------------+--------.
|                ITEMS                |
|=-------------+-------------+-------=|
|GLOBAL_HEADER |GROUP_HEADER |ITEM_KEY|
|=-------------+-------------+-------=|
|global header1|group_header1|1       |
|global header1|group_header1|2       |
|global header1|group_header1|3       |
|global header1|group_header2|1       |
|global header1|group_header2|2       |
|global header1|group_header2|3       |
|global header2|group_header1|1       |
|global header2|group_header1|2       |
|global header2|group_header1|3       |
|global header2|group_header2|1       |
|global header2|group_header2|2       |
|global header2|group_header2|3       |
'--------------+-------------+--------'
.--------------+-------------+--------.
|             MORE_ITEMS              |
|=-------------+-------------+-------=|
|GLOBAL_HEADER |GROUP_HEADER |ITEM_KEY|
|=-------------+-------------+-------=|
|global header1|group_header1|1       |
|null          |group_header1|2       |
|null          |group_header1|3       |
|null          |group_header2|1       |
|null          |group_header2|2       |
|null          |group_header2|3       |
'--------------+-------------+--------'
```

**Comment by jlolling** [comment]
I am close to fix that bug. I currently checking and improving all test cases and after finishing this, I will publish the fixed version.

**Comment by jlolling** [comment]
```
.--------------+-------------+--------.
|             MORE_ITEMS              |
|=-------------+-------------+-------=|
|GLOBAL_HEADER |GROUP_HEADER |ITEM_KEY|
|=-------------+-------------+-------=|
|global header1|group_header1|1       |
|global header1|group_header1|2       |
|global header1|group_header1|3       |
|global header1|group_header2|4       |
|global header1|group_header2|5       |
|global header1|group_header2|6       |
'--------------+-------------+--------'
```
