### ISSUE TITLE
CREATING JSON FORMAT IN TALEND (LOOPS AND ARRAYS IN SIDE AN OBJECT)

### ISSUE THREAD

**Issue by sudheereddy** [jlolling/talendcomp_tJSONDoc#29]
Hi  jlolling,
I have below use case and I am very new to this kind of objects in Talend , could you please help me in resolving this issue .

Use case :- I am trying to create a job which reads data from my sql and calls an rest api (which will insert/save data).
problem :-
I have been given specific format in which I need to call the API .
ex :- as below
Payload:
{
"uiid":"****",
"correlationId":"****",
"provider": [ (main loop element)
{

"createdOn": "2019-11-15T11:59:12.000+00:00",
"createdBy": null,
"updatedOn": "2019-11-15T11:59:12.000+00:00",
"updatedBy": null,
"providerLanguages": [
{
"languagetypeCd":null,
"providerSpeaksInd":null,
"prgrmTypeCd":"Medicaid",
"effectiveStartDate":"2019-04-01",
"effectiveEndDate":null,
"createdOn":"2019-11-15T11:59:12.000+00:00",
"createdBy":null,
"updatedOn":"2019-11-15T11:59:12.000+00:00",
"updatedBy":null
}
],
"providerSpeciality": [
{
"specialityCd":null,
"primarySpecialityInd":null,
"prgmTypeCd":null,
"effectiveStartDate":"2019-11-15",
"effectiveEndDate":null,
"createdOn":"2019-11-15T11:59:12.000+00:00",
"createdBy":"121",
"updatedOn":"2019-11-15T11:59:12.000+00:00",
"updatedBy":null
}

]
}
]
}
.....something like above .

the challenge is I have lang 1,lang,lan3, ... lang7 coming in diff columns and I need to use same coulumns repeated for lang 1 to lang 7 (created date , created by etc.. ) and it should be in arrray.

I would require help in designing the solution for this use case . would you please help me in this regard pls

**Comment by sudheereddy** [comment]
I have tried using tWriteJsonField object & tXmlMap to get to a solution.
tmysqlinput-->tmap (to join with tbuffer data)-->txmlmap/twritejsonfield(to convert row level data to desired json format)--> then trestclient (post to save data )
but not much of help ... am I missing something here .

**Comment by jlolling** [comment]
This is not an issue of the component.
