### ISSUE TITLE
Is it working on version 7.3 of Talend Open Studio for Data Integration

### ISSUE THREAD

**Issue by Benoit75** [jlolling/talendcomp_tJSONDoc#37]
Hello, 
Thank you for your amazing component. 
I'm would like to know if your current version of TJSONDoc (16.2) is working with Talend 7.3 ? 

I unseccfully  try to install it with exchange and with user compent i've got the "SLF4J: Class path contains multiple SLF4J bindings" issue

Regards
Benoît

**Comment by jlolling** [comment]
The components are working fine with Talend 7.3 and you can ignore the
Messages regarding slfj.
I will Update the components soon to get rid of it.

Best regards
Jan Lolling

Benoit75 <notifications@github.com> schrieb am Sa., 13. Feb. 2021, 12:51:

**Comment by Benoit75** [comment]
Hello Jan, 
Thank you for your reply.  
Because those Messages regarding slfj were blocking my job (in test mode) i comment in tJSONDocOpen_java.xml and tJSONDocInputStream_java.xml the line 

`  <!-- <IMPORT NAME="slf4j-simple" MODULE="slf4j-simple-1.6.1.jar" MVN="mvn:org.talend.libraries/slf4j-simple-1.6.1/6.0.0-SNAPSHOT" REQUIRED="true"/> -->`
(Conflict with org/apache/logging/log4j/log4j-slf4j-impl )
And it works fine now. 

Best Regards
Benoît
