### ISSUE TITLE
tJSONDocInputStream error

### ISSUE THREAD

**Issue by robstermn** [jlolling/talendcomp_tJSONDoc#39]
I'm getting the following error when trying to use the "tJSONDocInputStream" component?

`Starting job test_extract at 10:17 03/10/2021.
[statistics] connecting to socket on port 3972
[statistics] connected
[statistics] disconnected
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
	at de.jlo.talendcomp.json.streaming.JsonStreamParser.<clinit>(JsonStreamParser.java:27)
	at talendjobs.test_extract_0_1.test_extract.tJSONDocInputStream_1Process(test_extract.java:710)
	at talendjobs.test_extract_0_1.test_extract.runJobInTOS(test_extract.java:1396)
	at talendjobs.test_extract_0_1.test_extract.main(test_extract.java:1166)
**Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger**
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 4 more

Job test_extract ended at 10:17 03/10/2021. [Exit code  = 1]`

Thanks for any help.

**Comment by jlolling** [comment]
Could you please tell me which Version of Talend Studio do you running?

Best regards
Jan

Bob Veitch ***@***.***> schrieb am So., 3. Okt. 2021, 17:22:

**Comment by jlolling** [comment]
I can confirm the issue and will solve it asap.

**Comment by robstermn** [comment]
> I can confirm the issue and will solve it asap.

Jan

My Studio ver is: R2021-06-7.3.1

Thanks for the quick resposne.

Another question not related to this issue is a general question related to , Loop query.

Here is my JSON file format:
![image](https://user-images.githubusercontent.com/9891262/135849741-19f7f18e-11f6-41f0-96d1-f66135003d31.png)

And I'm trying to parse line_items and tenders, within each order.

I would like an output of:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/veitchb/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/veitchb/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



order_id | order_location | line_items_uid | line_items_catalog_object_id | tenders_id | tenders_transaction_id
-- | -- | -- | -- | -- | --
EwaBCV0bUpI3lIHTtdwbMB9eV | LC4E0W5JCHC1G | 4bf1bd23-b439-454e-a68a-0cc46bccd1af | IAJBOC2YSYVEBFQGKNZU73DG | hIkmBu9aG1uvHqjGL7m8kuCovaB | EwaBCV0bUpI3lIHTtdwbMB9eV
EwaBCV0bUpI3lIHTtdwbMB9eV | LC4E0W5JCHC1G | 0e19e156-d195-4fcc-98ea-9bfd343d9998 | ROYVJAO45EYMAQZDWIQELA3F | TpogsVrvDKKHQKLOhQbzjmIduaB | EwaBCV0bUpI3lIHTtdwbMB9eV



</body>

</html>


And I can't seem it get it to work, let me know if you could give me some pointers on this request.

Thanks again.

**Comment by jlolling** [comment]
Please checkout the latest release 16.7. This will fix the Log4J issue.

**Comment by jlolling** [comment]
Regarding your question about parsing. You have to extract line_items and tenders separately with a key in common (id).
After that you can join them.
