### ISSUE TITLE
de.jlo.talendcomp.json.JsonDocument n’est pas reconnu comme type valide

### ISSUE THREAD

**Issue by LHommeQuAVuLOurs** [jlolling/talendcomp_tJSONDoc#40]
Hello Jan,
First I'd like to thank you for all your very useful custom components.
I'm a big user of the tJsonDoc components myself but I just ran into an error I never saw before (right after installing a TAC patch : Patch_20210924_TPS-4913_v1-7.3.1 but I'm pretty sure this doesn't impact any of the studio features).

I have a compiling error : 
**de.jlo.talendcomp.json.JsonDocument n’est pas reconnu comme type valide**
(not recognized as a valid type)

I tried to reinstall the components or update them from 15.1 to 16.7, however it's still showing "15.1" in the advanced parameters... 
I've tried different methods : 
- Download the components and add them into my "custom components" (replacing the old ones), then reload the custom compnents folder from the preference settings in Studio
- Download and install components from the "Exchange" view directly inside the Studio.

I'm using Talend Data Management Platform Version: 7.3.1 Build id: R2021-09

To reproduce my error, create a new job with a tJsonDocOpen inside and open the "code" view.

I have no idea what you need to help me solve the issue. Feel free to contact me.

Best regards
Simon

**Comment by LHommeQuAVuLOurs** [comment]
Hi Jan
I'm sorry I reopen this issue because I have the same problem again : wrong
version shown in the advanced parameters and impossible to generate the
"code" view of a job. It's blank.
If I create a new job with a single tJsonDocOpen component in it, I have
the "de.jlo.talendcomp.json.JsonDocument n’est pas reconnu comme type
valide" error again.

Re-sync of pom files didn't solve the problem. Suppression of the workspace
didn't solve the problem... I'm out of solution now.

Do you have any idea I should try ?

Thank you
Simon

Le mar. 19 oct. 2021 à 17:54, Jan Lolling ***@***.***> a
écrit :

**Comment by jlolling** [comment]
Ho Simon,

Questions:
1. How do you install the components?
2. If you open the Component view for such a component, do you see there a orange area containing a button to load missing libraries?
3. Which java version do you running

If necessary we can have a zoom session to solve your issue.

Best regards
Jan

**Comment by LHommeQuAVuLOurs** [comment]
Since yesterday I found a workaround, and I think the problem was caused by
the "shared components" parameter.

I removed every custom component from the "shared list" then I changed the
custom component folder to target an empty one. Then I closed the studio,
deleted the workspace, re-open and specified the custom component folder
again and now it works, the good version is shown (16.7) and the jobs build.

I'm wondering if the old version wasn't stored in GIT because of the shared
components parameter ?

I'm running java 8 and  I didn't see any warning about missing library.
Everything looked fine in the component view but the version which was not
the version of the custom component folder (15.3).

Best regards
Simon

Le ven. 5 nov. 2021 à 18:25, Jan Lolling ***@***.***> a
écrit :

> Ho Simon,
>
> Questions:
> 1. How do you install the components?
> 2. If you open the Component view for such a component, do you see there a
> orange area containing a button to load missing libraries?
> 3. Which java version do you running
>
> If necessary we can have a zoom session to solve your issue.
>
> Best regards
> Jan
>

**Comment by jlolling** [comment]
Hi Simon
Glad to hear that. Thanks for sharing me your solution!
Best regards
Jan

LHommeQuAVuLOurs ***@***.***> schrieb am Fr., 5. Nov. 2021,
21:14:

> Since yesterday I found a workaround, and I think the problem was caused by
> the "shared components" parameter.
>
> I removed every custom component from the "shared list" then I changed the
> custom component folder to target an empty one. Then I closed the studio,
> deleted the workspace, re-open and specified the custom component folder
> again and now it works, the good version is shown (16.7) and the jobs
> build.
>
> I'm wondering if the old version wasn't stored in GIT because of the shared
> components parameter ?
>
> I'm running java 8 and I didn't see any warning about missing library.
> Everything looked fine in the component view but the version which was not
> the version of the custom component folder (15.3).
>
> Best regards
> Simon
>
> Le ven. 5 nov. 2021 à 18:25, Jan Lolling ***@***.***> a
> écrit :
>
> > Ho Simon,
> >
> > Questions:
> > 1. How do you install the components?
> > 2. If you open the Component view for such a component, do you see there
> a
> > orange area containing a button to load missing libraries?
> > 3. Which java version do you running
> >
> > If necessary we can have a zoom session to solve your issue.
> >
> > Best regards
> > Jan
> >
